Test.assert_equals(series_sum(1), "1.00")
Test.assert_equals(series_sum(2), "1.25")
Test.assert_equals(series_sum(3), "1.39")
Test.assert_equals(series_sum(5), "1.57")
Test.assert_equals(series_sum(0), "0.00")